"""public_id

Revision ID: 67502a6433d2
Revises: 
Create Date: 2021-11-30 18:07:31.219994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67502a6433d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('public_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'public_id')
    # ### end Alembic commands ###
